### ISSUE TITLE
#1 passwordEncorder error.

### ISSUE THREAD

**Issue by bbakzi** [TravelerOO/Backend#3]
userService passwordEncorder
암호화된 비밀번호와 입력비밀 번호를 비교를 제대로 하지 못함.

**Comment by seonminKim1122** [comment]
회원가입 시 passwordEncoder.encode() 를 2번 사용해 암호화가 2번 되고 있는 상황이었습니다.
암호화를 1번으로 줄이고 다시 로그인 시도하여 이상 없음을 확인했습니다.
